TRUNCATE TABLE notes RESTART IDENTITY CASCADE;
TRUNCATE TABLE parametres RESTART IDENTITY CASCADE;
TRUNCATE TABLE regles RESTART IDENTITY CASCADE;
TRUNCATE TABLE operateur RESTART IDENTITY CASCADE;
TRUNCATE TABLE correcteurs RESTART IDENTITY CASCADE;
TRUNCATE TABLE eleves RESTART IDENTITY CASCADE;
TRUNCATE TABLE matieres RESTART IDENTITY CASCADE;